### ISSUE TITLE
include Norway data?

### ISSUE THREAD

**Issue by late4marshmellow** [jannekalliola/MMM-FiElectricityPrice#2]
Hi @jannekalliola 

Great module you made here! :))
Been trying to look if i can make a version of your code to use the Norwegian data, but i have no clue in what i am doing :)

I figured that the Norway data with norwegian currency is found here: https://www.nordpoolgroup.com/api/marketdata/page/23?currency=NOK

thou data from  all 5 areas in norway is found here all thoghether, surely this is why your module cant fetch the data. 

i am in need of the Oslo data, maybe you please could help? :)

Thank you and happy holidays!

**Comment by jannekalliola** [comment]
Hello @late4marshmellow,

thank you for your kind words. I checked the data from that page and unfortunately it does not fit well with the current structure of the module.

The Finnish data contains the current and past seven days as columns, but the Norwegian data contains the Norwegian regions (Oslo, Kr.Sand, etc.) as columns. And there is no notion of the date, only times. The date can be found at the later stages of the data.

This implies two things:

1. the data parsing should be refactored to take into Norwegian (and other multiregion countries) into account.
2. Only one day data could be shown, and for example now, Dec 27th at 15.45 Finnish time, the API provides information for Dec 28th prices. Thus, the system would not be able to show the prices for the remaining of Dec 27th.

I tried to search for different parameters to set the exact region for a page, but with no luck so far. Should you be able to drill down to a single region in Norway, the system could work without changes.

But right now, the changes would be so extensive that I cannot promise that I'll implement them.

**Comment by wizz666** [comment]
Hi Janne 
How about the Swedish Data is it possible to implement in this or is it the same issue as with the Norwegian Data? 
If possible i am looking for a way for the region SE3

**Comment by jannekalliola** [comment]
Same problem, as also Sweden is divided into several zones.

**Comment by wizz666** [comment]
Ok thanks than i need to find an other solution for this.

**Comment by late4marshmellow** [comment]
hi @jannekalliola i've done updates on your codes to allow Oslo data, though i've hit a roadblock and now stuck..
the finish data process perfectly if i set dataSource to finnish, but somthing goes wrong with the Oslo data and i'm not quite sure. 
in my test thru node.js, all the output of res seems fine, but when run in MMM, it just fails...
maybe you see why i cant process the data?

please check my fork? :)
https://github.com/late4marshmellow/MMM-NoElectricityPrice

and if this leads you to be able to support other data in much more ease, please feel free to use my work 👍

**Comment by late4marshmellow** [comment]
@jannekalliola 
leting you know i've made some progress...seems i didnt forward the payload for Oslo / Finnish switcher from dataSource

`	socketNotificationReceived: function(notification, payload) {
        if(notification === 'GET_PRICEDATA') {
            this.getPriceData(payload.url, payload.hourOffset, payload.priceOffset, payload.priceMultiplier, payload.dataSource);
        }
	},
`

 i'll keep you posted 😄

**Comment by late4marshmellow** [comment]
@jannekalliola it is now working, for both all EU data, i've decided to work on this abit more extendig to whole EU and therefore it will be a fork, you are still welcome to do a pull though 😄 

@wizz666 my fork should now work with your SE3

**Comment by jannekalliola** [comment]
@late4marshmellow @wizz666 Thank you for your work on this. I've been swamped with various other stuff recently and now got time to check this out.

I could merge your changes back to main @late4marshmellow, if that is ok with you.

Further, I've been thinking of changing the source to https://www.entsoe.eu/data/transparency-platform/ or https://sahkotin.fi/api, as there could be also needs to use historic data. Any thoughts about this?

**Comment by late4marshmellow** [comment]
@jannekalliola i've been looking into entsoe.eu myself. 
i would guess should not be any issue for Finland as you use euro. 
Though for Norway, Sweden or other countries that still has other currencies this would be problematic. 
Here we would need to adjust with some sort of exchange rate. Resulting in that prices would never be accurate. 

anyway with my update fetching historical data is achievable since we fetch data per day. 
this can also be set as needed in code.

you are welcome to use my changes back to main, though i've made several changes that might need you to inspect the code carefully before merging. 

Yesterday i even changed the logic behind how safe and alert limit works. 
added several lines to settings and allowed for line or bar chart
